<#setting number_format="#">
Me.${name}.Font = New System.Drawing.Font("MS UI Gothic", 11.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(128, Byte))
Me.${name}.AutoSize = False
Me.${name}.Location = New System.Drawing.Point(${left}, ${top})
Me.${name}.Name = "${name}"
Me.${name}.Size = New System.Drawing.Size(${width}, ${height})
Me.${name}.TabIndex = ${tabIndex}
Me.${name}.Text = "${text!''}"
Me.${name}.TextAlign = System.Drawing.ContentAlignment.MiddleRight
